name: cdds
description: A drug counterfeit detection system project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  barcode_scan2: ^4.1.4
  bloc: ^7.2.1
  cloud_firestore: ^2.5.3
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  date_format: ^2.0.4
  equatable: ^2.0.3

  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0

  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  hydrated_bloc: ^7.1.0
  json_annotation: ^4.1.0
  material_floating_search_bar: ^0.3.4
  path_provider: ^2.0.5
  qr_flutter: ^4.0.0
  salomon_bottom_bar: ^3.1.0
  sign_in_with_apple: ^3.2.0
  sizer: ^2.0.15
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^5.0.2
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true

  image_path: "assets/images/cddslogo.jpeg"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
